---
dist: focal
language: generic

services:
  - docker

jobs:
  include:
       - name: "IBM Z building a breadth-first search by Montana Mendy on Python 3.7"
       os: linux
       arch: s390x
       language: python
       python: 3.7
       before_install:
       - hostnamectl
       - python --version
       - docker --version
       install: skip
       before_script: skip
       script: python ./bfs.py
       env:
       - LIB_PATH="/usr/bin/shared/x86_64/v1"
       
       - name: "IBM Z building a depth-first search made by Montana Mendy on Python 3.9"
       os: linux
       dist: bionic
       arch: s390x
       language: python
       python: 3.9
       before_install:
       - hostnamectl
       - python --version
       - docker --version
       install: skip
       before_script: skip
       script: python ./dfs.py
       env:
       - LIB_PATH="/usr/bin/shared/x86_64/v1"

before_install: skip
install: skip
script: skip
after_success: skip
